import turtle
t = turtle.Turtle()

t.shape('turtle')

t.color('red')
t.forward(40)
t.color('orange')
t.forward(40)
t.color('yellow')
t.forward(40)
t.color('green')
t.forward(40)
t.color('blue')
t.forward(40)
t.color('skyblue')
t.forward(40)
t.color('pink')
t.forward(40)
t.color('hotpink')
t.forward(40)
t.color('purple')
t.forward(40)

t.left(90)

t.color('red')
t.forward(40)
t.color('orange')
t.forward(40)
t.color('yellow')
t.forward(40)
t.color('green')
t.forward(40)
t.color('blue')
t.forward(40)
t.color('skyblue')
t.forward(40)
t.color('pink')
t.forward(40)
t.color('hotpink')
t.forward(40)
t.color('purple')
t.forward(40)

t.left(90)

t.color('red')
t.forward(40)
t.color('orange')
t.forward(40)
t.color('yellow')
t.forward(40)
t.color('green')
t.forward(40)
t.color('blue')
t.forward(40)
t.color('skyblue')
t.forward(40)
t.color('pink')
t.forward(40)
t.color('hotpink')
t.forward(40)
t.color('purple')
t.forward(40)

t.left(90)

t.color('red')
t.forward(40)
t.color('orange')
t.forward(40)
t.color('yellow')
t.forward(40)
t.color('green')
t.forward(40)
t.color('blue')
t.forward(40)
t.color('skyblue')
t.forward(40)
t.color('pink')
t.forward(40)
t.color('hotpink')
t.forward(40)
t.color('purple')
t.forward(40)
